spring:
  application:
    name: Produtos
  datasource:
    url: jdbc:h2:mem:produtos
    username: produtos
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  H2:
    console:
    enabled: true
    path: /h2-console
